spring.application.name=demo

SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}

sentry.dsn=https://abf3900ec612d5b2a39f56ae97ff1698@o4511482028556288.ingest.de.sentry.io/4511482034782288
# Add data like request headers and IP for users,
# see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
sentry.send-default-pii=true

linear.api = ${LINEAR_API_KEY}

sonar.api.key = ${SONAR_API_KEY}

server.port=8081